FROM mhart/alpine-node:8

RUN npm install -g serverless --ignore-scripts && \
    npm install serverless-offline

ENV AWS_ACCESS_KEY_ID AKIAJTV2F6S6EP4YG3RA
ENV AWS_SECRET_ACCESS_KEY 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
